global-config:
  verbose: True
  logs: True
  logs-file: logs.log

crawler-config:
  max-urls: 100
  base-url: https://www.ensai.fr
  pages-db: data/pages.db
  politeness-delay: 3
  n-threads: 10

indexer-config:
  pages-db: data/pages.db
  index-db: data/index.db
  model: fr_core_news_sm
  limit: 1000
  n-threads: 10

api-config:
  index-db: data/index.db